name: agri_easy
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"
dependencies:
  # Common dependencies
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2

  # help_supp dependencies
  socket_io_client: ^3.0.0
  shared_preferences: ^2.0.15
  path_provider: ^2.0.12 
  video_player: ^2.9.2 
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  photo_view: ^0.15.0
  flutter_background: ^1.3.0+1
  image: ^4.2.0

  # agri_easy dependencies
  animated_text_kit: ^4.2.2
  webview_flutter_android: ^4.0.0
  flutter_localizations:
    sdk: flutter
  curved_navigation_bar: ^1.0.6
  webview_flutter: ^4.0.1
  logger: ^2.4.0
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.14.1
  flutter_spinkit: ^5.2.1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get: ^4.6.6
  intl: ^0.19.0
  modal_progress_hud_nsn: ^0.5.1
  provider: ^6.1.2
  sleek_circular_slider: ^2.0.1
  translator: ^1.0.0
  string_scanner: ^1.2.0
  speech_to_text: ^7.0.0
video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  flutter_gen: ^5.7.0
  flutter_lints: ^5.0.0
  test_api: ^0.7.2
  intl_utils: ^2.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/weather/
    - assets/images/
    - jsonfile/
    - assets/
    - assets/fonts/

  fonts:
    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf
        - asset: assets/fonts/Lobster-Regular.ttf
          weight: 700